# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  cmagency:
    image: andrejnenadic/cmagency-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - 5055:5055
